### ISSUE TITLE
picoFriends error

### ISSUE THREAD

**Issue by illum1n4ti** [TekNoLogic/picoFriends#4]
Message: Interface\AddOns\picoFriends\tooltip.lua:63: attempt to call global 'BNGetToonInfo' (a nil value)
Time: Wed Apr  6 00:40:03 2016
Count: 3
Stack: Interface\AddOns\picoFriends\tooltip.lua:63: in function <Interface\AddOns\picoFriends\tooltip.lua:44>
(tail call): ?

Locals: self = <unnamed> {
 0 = <userdata>
 TextUpdate = <function> defined @Interface\AddOns\tekBlocks\tekBlocks.lua:16
 SetDObjScript = <function> defined @Interface\AddOns\tekBlocks\tekBlocks.lua:36
 text = <unnamed> {
 }
 IconUpdate = <function> defined @Interface\AddOns\tekBlocks\tekBlocks.lua:22
 icon = <unnamed> {
 }
 dataobj = <table> {
 }
}
mylevel = 100
bnet_total = 28
bnet_online = 1
wow_total = 1
wow_online = 0
(for index) = 1
(for limit) = 1
(for step) = 1
i = 1
presenceID = 6
presenceName = "|Kf19|ksinned79|k"
battleTag = "sinned79#1833"
isBattleTagPresence = true
toonName = nil
toonID = 32
client = "App"
online = true
lastOnline = 1459895155
isAFK = false
isDND = false
broadcastText = ""
note = false
isFriend = true
broadcastTime = 0
(*temporary) = nil
(*temporary) = 32
(*temporary) = "attempt to call global 'BNGetToonInfo' (a nil value)"
tip = <unnamed> {
 AddLine = <function> defined @Interface\AddOns\picoFriends\externals\ui-multicolumn-tooltip.lua:112
 AddMultiLine = <function> defined @Interface\AddOns\picoFriends\externals\ui-multicolumn-tooltip.lua:127
 AnchorTo = <function> defined @Interface\AddOns\picoFriends\externals\ui-multicolumn-tooltip.lua:95
 numlines = 2
 Clear = <function> defined @Interface\AddOns\picoFriends\externals\ui-multicolumn-tooltip.lua:102
 0 = <userdata>
 cols = <table> {
 }
}
factiontags = <table> {
 Horde = " "
 Alliance = " "
}
AddDetailedLine = <function> defined @Interface\AddOns\picoFriends\tooltip.lua:14
ns = <table> {
 BN_FRIEND_INFO_CHANGED = <function> defined @Interface\AddOns\picoFriends\picoFriends.lua:66
 CHAT_MSG_SYSTEM = <function> defined @Interface\AddOns\picoFriends\picoFriends.lua:59
 BN_FRIEND_ACCOUNT_ONLINE = <function> defined @Interface\AddOns\picoFriends\picoFriends.lua:66
 StartRepeatingTimer = <function> defined @Interface\AddOns\picoFriends\externals\timer.lua:32
 RegisterEvent = <function> defined @Interface\AddOns\picoFriends\externals\events.lua:8
 UnregisterAllEvents = <function> defined @Interface\AddOns\picoFriends\externals\events.lua:19
 BN_FRIEND_LIST_SIZE_CHANGED = <function> defined @Interface\AddOns\picoFriends\picoFriends.lua:66
 BN_FRIEND_ACCOUNT_OFFLINE = <function> defined @Interface\AddOns\picoFriends\picoFriends.lua:66
 dataobj = <table> {
 }
 NewTooltip = <function> defined @Interface\AddOns\picoFriends\externals\ui-multicolumn-tooltip.lua:51
 FRIENDLIST_UPDATE = <function> defined @Interface\AddOns\picoFriends\picoFriends.lua:66
 StopRepeatingTimer = <function> defined @Interface\AddOns\picoFriends\externals\timer.lua:39
 L = <table> {
 }
 UnregisterEvent = <function> defined @Interface\AddOns\picoFriends\externals\events.lua:14
 StartTimer = <function> defined @Interface\AddOns\picoFriends\externals\timer.lua:26
}

**Comment by tekkub** [comment]
This should be fixed now.
